# app
FROM eclipse-temurin:17

RUN mkdir /opt/app

COPY target/ejemplobd-0.0.1-SNAPSHOT.jar /opt/app/canciones.jar

CMD ["java", "-jar", "/opt/app/canciones.jar", "--spring.profiles.active=docker"]



